# Library documentation: http://tactician.thephpleague.com/
# Bundle documentation: https://github.com/thephpleague/tactician-bundle/blob/v1.0/README.md
tactician:
    default_bus: 'command'
    commandbus:
#        query:
#            method_inflector: tactician.handler.method_name_inflector.handle_class_name
#            middleware:
#                - tactician.middleware.validator
#                - tactician.commandbus.query.middleware.command_handler
        command:
            method_inflector: tactician.handler.method_name_inflector.handle_class_name
            middleware:
                # Security middleware - https://github.com/thephpleague/tactician-bundle#security-middleware-tacticianmiddlewaresecurity
                #                - tactician.middleware.security
                # Validator middleware - https://github.com/thephpleague/tactician-bundle/tree/v1.0#validator-middleware-tacticianmiddlewarevalidator
#                - tactician.middleware.validator
                # Locking middleware - http://tactician.thephpleague.com/plugins/locking-middleware/
                #                - tactician.middleware.locking
                # Doctrine transactional middleware, requires additional package - https://github.com/thephpleague/tactician-doctrine
                #                - tactician.middleware.doctrine
                - tactician.commandbus.command.middleware.command_handler
