sonata_admin:
    title: 'MediaMonks'
    security:
        handler: sonata.admin.security.handler.role
    templates:
        user_block: 'admin/user_block.html.twig'
    dashboard:
        groups:
            admin.group.global:
                label: Global
                items:
                    - admin.profile
                    - admin.user
                roles: [ ROLE_ROOT ]

services:
    admin.profile:
        class: App\Admin\ProfileAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Global, label: Site Users}
        arguments: [ ~, App\Entity\Profile, ~]
    admin.user:
        class: App\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Global, label: CMS Users}
        arguments: [ ~, App\Entity\User, ~]
